name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  x86-build:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [nightly-2022-10-29]
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        rustup toolchain install ${{ matrix.rust }} --no-self-update --profile=minimal
        rustup default ${{ matrix.rust }}
        
    - name: x
      run: |
        echo "dbg"

    - name: Step for Mac
      if: runner.os == 'macOS'
      run: cargo build --bin mm2 --profile ci --target x86_64-apple-darwin

    - name: Step for Linux & Win
      if: runner.os != 'macOS'
      run: cargo build --bin mm2 --profile ci
