name: Format and Lint
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  fmt-and-x86-64-lint:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: [nightly-2022-10-29]
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        rustup toolchain install ${{ matrix.rust }} --no-self-update --profile=minimal --component rustfmt clippy
        rustup default ${{ matrix.rust }}

    - name: fmt check
      run: cargo fmt -- --check

    - name: x86-64 code lint
      run: cargo clippy --profile ci -- --D warnings

  wasm-lint:
    timeout-minutes: 25
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly-2022-10-29]
    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        rustup toolchain install ${{ matrix.rust }} --no-self-update --profile=minimal --component rustfmt clippy
        rustup default ${{ matrix.rust }}
        rustup target add wasm32-unknown-unknown

    - name: wasm code lint
      run: cargo clippy --target wasm32-unknown-unknown --profile ci -- --D warnings
